
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package genSources;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int T_MAIOR_IGUAL = 35;
  public static final int T_WHILE = 20;
  public static final int T_ABRE_PARENTESES = 6;
  public static final int T_ELSE = 19;
  public static final int T_READ = 22;
  public static final int T_THEN = 18;
  public static final int T_FALSE = 15;
  public static final int T_INT = 37;
  public static final int T_NAO_IGUAL = 32;
  public static final int T_MENOR_QUE = 34;
  public static final int T_DOIS_PONTOS = 11;
  public static final int T_NOT = 26;
  public static final int T_AND = 24;
  public static final int T_PONTO_E_VIRGULA = 10;
  public static final int T_PROCEDURE = 13;
  public static final int T_DIV = 27;
  public static final int T_NUM = 39;
  public static final int T_DO = 21;
  public static final int T_VIRGULA = 9;
  public static final int T_FECHA_PARENTESES = 7;
  public static final int EOF = 0;
  public static final int T_PONTO = 12;
  public static final int T_WRITE = 23;
  public static final int error = 1;
  public static final int T_IGUAL = 31;
  public static final int T_ATRIBUICAO = 8;
  public static final int T_BEGIN = 3;
  public static final int T_BOOL = 38;
  public static final int T_PROGRAM = 2;
  public static final int T_MAIS = 28;
  public static final int T_MENOS = 29;
  public static final int T_MULTIPLICACAO = 30;
  public static final int T_OR = 25;
  public static final int T_END = 4;
  public static final int T_IDENT = 40;
  public static final int T_TRUE = 16;
  public static final int T_IF = 17;
  public static final int T_FUNCTION = 14;
  public static final int T_VAR = 5;
  public static final int T_MAIOR_QUE = 33;
  public static final int T_MENOR_IGUAL = 36;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "T_PROGRAM",
  "T_BEGIN",
  "T_END",
  "T_VAR",
  "T_ABRE_PARENTESES",
  "T_FECHA_PARENTESES",
  "T_ATRIBUICAO",
  "T_VIRGULA",
  "T_PONTO_E_VIRGULA",
  "T_DOIS_PONTOS",
  "T_PONTO",
  "T_PROCEDURE",
  "T_FUNCTION",
  "T_FALSE",
  "T_TRUE",
  "T_IF",
  "T_THEN",
  "T_ELSE",
  "T_WHILE",
  "T_DO",
  "T_READ",
  "T_WRITE",
  "T_AND",
  "T_OR",
  "T_NOT",
  "T_DIV",
  "T_MAIS",
  "T_MENOS",
  "T_MULTIPLICACAO",
  "T_IGUAL",
  "T_NAO_IGUAL",
  "T_MAIOR_QUE",
  "T_MENOR_QUE",
  "T_MAIOR_IGUAL",
  "T_MENOR_IGUAL",
  "T_INT",
  "T_BOOL",
  "T_NUM",
  "T_IDENT"
  };
}

